version: '3.9'

services:
  go_container:
    container_name: go_container
    build:
      context: .
      dockerfile: connect-go.dockerfile
    tty: true
    restart: 'always'
    volumes:
      - ".:/usr/src/app"
    networks:
      - local
    ports:
      - "8080:8080"

networks:
  local: {}