version: "3.9"

services:
  rust_container:
    container_name: rust_container
    build:
      context: ./rocket_example
      dockerfile: rust.dockerfile
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - "./rocket_example:/usr/src/myapp"
    networks:
      - local

networks:
  local: {}
