version: '3.9'

services:
  api_server:
    build: ./api
    container_name: api_server
    tty: true
    restart: always
    volumes:
      - ./api:/usr/src/app
    networks:
      - local
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - local
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - local
    volumes:
      - kibanadata:/usr/share/kibana/config

volumes:
  pgdata: {}
  elasticsearchdata: {}
  kibanadata: {}

networks:
  local: {}
